dist: trusty
language: php
php:
  - 5.6
  - hhvm
  - 7.0
  - 7.1
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
before_script:
  - composer self-update
  - composer install
script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover